### ISSUE TITLE
write getting started documentation for face landmark app

### ISSUE THREAD

**Issue by cdiddy77** [cdiddy77/react-native-mediapipe#101]
Need to fill out [this page](https://github.com/cdiddy77/react-native-mediapipe/blob/main/docsite/docs/api_pages/face-landmark-detection.md)

**Comment by michellrodriguez08** [comment]
Where do I get the information from? Or is it the same as the object detection one?

**Comment by cdiddy77** [comment]
https://discord.com/channels/1214648902473490523/1214648902473490526/1245761646379405383

**Comment by cdiddy77** [comment]
> Where do I get the information from? Or is it the same as the object detection one?

https://discord.com/channels/1214648902473490523/1214648902473490526/1245761646379405383
