### ISSUE TITLE
Bad meta description in docsite

### ISSUE THREAD

**Issue by rorleth** [cdiddy77/react-native-mediapipe#122]
If you paste a link into e.g. Teams, or if you look at search results, it displays the page title and then a description, like so:
![image](https://github.com/cdiddy77/react-native-mediapipe/assets/12026194/d65b3179-80f7-4996-823d-c0961d1894fa)

The issue is that it says "Description will go into a meta tag in" - that comes from index.tsx:
    <Layout
      title={`Hello from ${siteConfig.title}`}
      description="Description will go into a meta tag in <head />">

Note that the "<head />" part isn't displayed because it's an empty HTML tag.

**Comment by cdiddy77** [comment]
Thank you @LeviAdamMiller
