### ISSUE TITLE
small issues in contributing.md

### ISSUE THREAD

**Issue by rorleth** [cdiddy77/react-native-mediapipe#52]
The "install dependencies" section is empty:
<img width="1036" alt="Screenshot 2024-04-18 at 6 56 48 PM" src="https://github.com/cdiddy77/react-native-mediapipe/assets/12026194/fca70d84-69f1-4740-8527-fe7c30538ee9">

The example directory is gone - this one says "examples":
<img width="454" alt="Screenshot 2024-04-18 at 6 58 40 PM" src="https://github.com/cdiddy77/react-native-mediapipe/assets/12026194/7175f31e-4767-40a0-ac6a-fd27c696048d">

**Comment by sukanvisapearyoo** [comment]
#21
