### ISSUE TITLE
small issue in readme.md

### ISSUE THREAD

**Issue by rorleth** [cdiddy77/react-native-mediapipe#53]
typo in plugins statement - it's worklets not wordless:
<img width="335" alt="Screenshot 2024-04-18 at 7 00 18 PM" src="https://github.com/cdiddy77/react-native-mediapipe/assets/12026194/ccd8408b-2c84-4425-94e1-b7d65d89c0de">

**Comment by shackerman** [comment]
Fixed, sent the pull request!
